# general settings
name: v9_7_5_3_scale2  
model_type: CSDLLSRv4  
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage 
    dataroot_gt: /dataset/RELLISUR-Dataset/Train/NLHR-Duplicates/X2
    dataroot_lq: /dataset/RELLISUR-Dataset/Train/LLLR
    # dataroot_lh: /dataset/RELLISUR-Dataset/Train/NLHR-Duplicates/X1
    geometric_augs: true
    use_grayatten: false
    use_ueatten: false
    use_multask: false
    use_illguidance: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

 
    mini_batch_sizes: [8,5,4,2,1,1]   
    iters: [46000,32000,24000,18000,18000,12000]
    gt_size: 384   # Max patch size for progressive training. 384
    gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.  
 

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /dataset/RELLISUR-Dataset/Test_crop/NLHR-Duplicates/X2
    dataroot_lq: /dataset/RELLISUR-Dataset/Test_crop/LLLR
    io_backend:
      type: disk
    use_grayatten: false
    use_illguidance: true

# network structures
network_g:
  type: CSDLLSRNetv9_7_5 
 # MIRNetv2Retinexv3
  inp_channels: 3
  out_channels: 3
  n_feat: 64
  scale: 2


# path
path:
  pretrain_network_g: ~  
  strict_load_g: true
  resume_state: ~  

# training settings
train:
  total_iter: 150000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 0.01
    style_weight: 0
    range_norm: false
    criterion: l1

  IllSmoothL1_opt:
    type: SmoothL1
    loss_weight: 1 


  IllColor_opt:
    type: IllColor
    loss_weight: 1 

# validation settings
val:
  window_size: 4
  val_freq: !!float 3e3
  save_img: true
  rgb2bgr: true
  use_image: true
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 3e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500